CREATE  TABLE IF NOT EXISTS `LAA0130613-lanevok`.`textres` (
  `id` INT(11) NOT NULL ,
  `text` VARCHAR(140) NOT NULL ,
  `created` TIMESTAMP NULL DEFAULT NULL ,
  `updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `posted` TIMESTAMP NULL DEFAULT NULL ,
  `user` VARCHAR(20) NULL DEFAULT NULL ,
  `ban` TINYINT(1) NOT NULL DEFAULT '0' ,
  `cnt` INT(11) NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `text_UNIQUE` (`text` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );